services:
  - type: web
    name: sokohub
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn sokohub.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sokohub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: sokohub-db
    plan: free
